[package]
name = "aoc2019"
version = "0.1.0"
authors = ["Damon Barry <damonbarry@outlook.com>"]
edition = "2018"

[dependencies]
failure = "0.1.6"
failure_derive = "0.1.6"
libmath = "0.2.1"
num = "0.2.0"
petgraph = "0.5.0"